// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgVR_x3IU191G85TwzShhnwQ9LGxgWidg',
    appId: '1:498210949236:web:eb5943198a741020212921',
    messagingSenderId: '498210949236',
    projectId: 'teonglee-first-project',
    authDomain: 'teonglee-first-project.firebaseapp.com',
    storageBucket: 'teonglee-first-project.appspot.com',
    measurementId: 'G-B841G1T8ZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJPJ8hQmOTMQxGqR_l_T7J-o9KYH_ao0U',
    appId: '1:498210949236:android:a0fd3c45cb5ed4eb212921',
    messagingSenderId: '498210949236',
    projectId: 'teonglee-first-project',
    storageBucket: 'teonglee-first-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgfMNqopZcHANI1NFXAQ5rkKygQQUt1tw',
    appId: '1:498210949236:ios:49d9878549f8d306212921',
    messagingSenderId: '498210949236',
    projectId: 'teonglee-first-project',
    storageBucket: 'teonglee-first-project.appspot.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgfMNqopZcHANI1NFXAQ5rkKygQQUt1tw',
    appId: '1:498210949236:ios:49d9878549f8d306212921',
    messagingSenderId: '498210949236',
    projectId: 'teonglee-first-project',
    storageBucket: 'teonglee-first-project.appspot.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgVR_x3IU191G85TwzShhnwQ9LGxgWidg',
    appId: '1:498210949236:web:3ebedaf8c2347fc5212921',
    messagingSenderId: '498210949236',
    projectId: 'teonglee-first-project',
    authDomain: 'teonglee-first-project.firebaseapp.com',
    storageBucket: 'teonglee-first-project.appspot.com',
    measurementId: 'G-KGPYBDCE9N',
  );
}
